#!/bin/sh
#
### Estimating GDT_HA and GDT_TS from comparison of different proteins using LGA structural alignment:
#
# Usage: ./run_GDT_estimation  pdb1  pdb2  OUT  
#

# Output OUT: 0 - no coordinates, 1 - rotated first structure, 2 - two aligned structures
OUT=0
if [ $3 -gt 0 ]; then
  OUT=$3
else
  OUT=0
fi

mol2process=GDT.$1\.$2

collect_PDB.pl $1 > MOL2/$mol2process
collect_PDB.pl $2 >> MOL2/$mol2process

# Calculate structural alignment
./lga -4 -d:5.0 -o0 -gdc -lga_m -stral $mol2process > RESULTS/$mol2process.res

# Use LGA alignment records to select residue-residue correspondences for GDT calculations
grep "^LGA " RESULTS/$mol2process.res >> MOL2/$mol2process
./lga -3 -sia -d:5.0 -o$OUT -al $mol2process > RESULTS/$mol2process.gdt_res

# Collect data from calculations
NB12=`grep "^SUMMARY(LGA)" RESULTS/$mol2process.res | perl -ane '@L=split(/[\ ]+/,$_); printf "%s:%s",$L[1],$L[2]'`
NB=`grep "^SUMMARY(GDT)" RESULTS/$mol2process.gdt_res | perl -ane '@L=split(/[\ ]+/,$_); printf "%s",$L[2]'`
GDT=`cat RESULTS/$mol2process.gdt_res | grep "GDT PERCENT_AT" | perl -ane '@LINE=(@F);$V1=($LINE[2]+$LINE[3]+$LINE[5]+$LINE[9])/4.0;$V2=($LINE[3]+$LINE[5]+$LINE[9]+$LINE[17])/4.0;printf "%6.2f:%6.2f",$V1,$V2;'`

# Create output
cat RESULTS/$mol2process.res | grep -v "# END of job"
echo "# Estimated values of GDT_HA and GDT_TS from LGA sequence independent analysis:"
echo "$NB12 $NB $GDT" | perl -ane '@L=split(/[\ \:]+/,$_); printf "GDT_HA = %6.2f  GDT_TS = %6.2f\n\n",$L[3]*$L[2]/$L[1],$L[4]*$L[2]/$L[1];'
echo "# END of job"

if [ $OUT -gt 0 ]; then
  grep -v "^LGA " TMP/$mol2process.pdb | egrep -v -e "REMARK   GDT and LCS analysis" -e "REMARK   FIXED Atom-Atom correspondence" -e "REMARK   LGA parameters:" -e "REMARK   #CA        N1   N2" -e "REMARK   SUMMARY:"
fi
